# Generated by Django 4.0 on 2022-01-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
    ]
