# Generated by Django 4.0 on 2022-01-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0002_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
