# Generated by Django 4.0 on 2022-01-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0004_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
