# Generated by Django 4.0 on 2022-01-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainPages.category'),
        ),
    ]
