# Generated by Django 4.0 on 2022-01-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0007_course_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categoryId',
        ),
        migrations.AddField(
            model_name='course',
            name='categoryId',
            field=models.ManyToManyField(to='mainPages.Category'),
        ),
    ]
