# Generated by Django 4.0 on 2022-01-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPages', '0008_remove_course_categoryid_course_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categoryId',
            field=models.ManyToManyField(blank=True, to='mainPages.Category'),
        ),
    ]
