# Generated by Django 4.0 on 2022-01-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
